# Generated by Django 2.2.27 on 2022-03-07 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shoot_setup.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gear', '0002_auto_20220307_1151'),
        ('project', '0007_auto_20220303_1308'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShootSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to=shoot_setup.models.ShootSetup.image_upload_dir, verbose_name='Background Image')),
                ('reply', models.CharField(blank=True, max_length=100, verbose_name='Reply')),
                ('audio', models.CharField(blank=True, max_length=100, verbose_name='Audio')),
                ('grfx', models.CharField(blank=True, max_length=100, verbose_name='GRFX')),
                ('client', models.CharField(blank=True, max_length=100, verbose_name='Client')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoot_director', to=settings.AUTH_USER_MODEL, verbose_name='Director')),
                ('gears', models.ManyToManyField(blank=True, related_name='shoot_camera', to='gear.Camera', verbose_name='Shoot Cameras')),
                ('on_sight', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='on_sight_user', to=settings.AUTH_USER_MODEL, verbose_name='On Sight')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoot_project', to='project.Project', verbose_name='Shoot Project')),
                ('technical_deirector', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoot_technical_director', to=settings.AUTH_USER_MODEL, verbose_name='Technical Director')),
            ],
        ),
    ]
