# Generated by Django 2.2.27 on 2022-03-07 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoot_setup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shootsetup',
            old_name='technical_deirector',
            new_name='technical_director',
        ),
    ]
