# Generated by Django 2.2.27 on 2022-03-13 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoot_setup', '0002_auto_20220307_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shootsetup',
            name='on_sight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='on_sight_user', to=settings.AUTH_USER_MODEL, verbose_name='On Sight'),
        ),
        migrations.AlterField(
            model_name='shootsetup',
            name='technical_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoot_technical_director', to=settings.AUTH_USER_MODEL, verbose_name='Technical Director'),
        ),
    ]
