# Generated by Django 2.2.27 on 2022-03-13 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoot_setup', '0003_auto_20220313_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shootsetup',
            name='reply',
        ),
        migrations.AddField(
            model_name='shootsetup',
            name='replay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Replay', to=settings.AUTH_USER_MODEL, verbose_name='Replay'),
        ),
        migrations.AlterField(
            model_name='shootsetup',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio', to=settings.AUTH_USER_MODEL, verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='shootsetup',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='shootsetup',
            name='grfx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grfx', to=settings.AUTH_USER_MODEL, verbose_name='GRFX'),
        ),
    ]
