# Generated by Django 2.2.27 on 2022-03-15 09:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoot_setup', '0004_auto_20220313_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='shootsetup',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
