# Generated by Django 2.2.27 on 2022-04-03 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoot_setup', '0005_shootsetup_properties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shootsetup',
            name='gears',
        ),
    ]
