# Generated by Django 2.2.27 on 2022-04-12 08:53

from django.db import migrations, models
import django.db.models.deletion
import shoot_setup.models


class Migration(migrations.Migration):

    dependencies = [
        ('shoot_setup', '0006_remove_shootsetup_gears'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shootsetup',
            name='background_image',
        ),
        migrations.AddField(
            model_name='shootsetup',
            name='selected_shoot_image',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ShootImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to=shoot_setup.models.ShootImage.image_upload_dir, verbose_name='Background Image')),
                ('shoot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoot_setup', to='shoot_setup.ShootSetup')),
            ],
        ),
    ]
