# Generated by Django 2.2.27 on 2022-08-12 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoot_setup', '0007_auto_20220412_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shootimage',
            name='shoot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoot_setup_background', to='shoot_setup.ShootSetup'),
        ),
    ]
