# Generated by Django 2.2.27 on 2022-07-13 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoot_setup', '0007_auto_20220412_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='shootsetup',
            name='producer',
            field=models.ManyToManyField(related_name='shoot_producer', to=settings.AUTH_USER_MODEL, verbose_name='Producer'),
        ),
        migrations.RemoveField(
            model_name='shootsetup',
            name='audio',
        ),
        migrations.AddField(
            model_name='shootsetup',
            name='audio',
            field=models.ManyToManyField(blank=True, null=True, related_name='audio', to=settings.AUTH_USER_MODEL, verbose_name='Audio'),
        ),
        migrations.RemoveField(
            model_name='shootsetup',
            name='client',
        ),
        migrations.AddField(
            model_name='shootsetup',
            name='client',
            field=models.ManyToManyField(blank=True, null=True, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.RemoveField(
            model_name='shootsetup',
            name='director',
        ),
        migrations.AddField(
            model_name='shootsetup',
            name='director',
            field=models.ManyToManyField(related_name='shoot_director', to=settings.AUTH_USER_MODEL, verbose_name='Director'),
        ),
        migrations.RemoveField(
            model_name='shootsetup',
            name='grfx',
        ),
        migrations.AddField(
            model_name='shootsetup',
            name='grfx',
            field=models.ManyToManyField(blank=True, null=True, related_name='grfx', to=settings.AUTH_USER_MODEL, verbose_name='GRFX'),
        ),
        migrations.RemoveField(
            model_name='shootsetup',
            name='on_sight',
        ),
        migrations.AddField(
            model_name='shootsetup',
            name='on_sight',
            field=models.ManyToManyField(blank=True, null=True, related_name='on_sight_user', to=settings.AUTH_USER_MODEL, verbose_name='On Sight'),
        ),
        migrations.RemoveField(
            model_name='shootsetup',
            name='replay',
        ),
        migrations.AddField(
            model_name='shootsetup',
            name='replay',
            field=models.ManyToManyField(blank=True, null=True, related_name='Replay', to=settings.AUTH_USER_MODEL, verbose_name='Replay'),
        ),
        migrations.RemoveField(
            model_name='shootsetup',
            name='technical_director',
        ),
        migrations.AddField(
            model_name='shootsetup',
            name='technical_director',
            field=models.ManyToManyField(blank=True, null=True, related_name='shoot_technical_director', to=settings.AUTH_USER_MODEL, verbose_name='Technical Director'),
        ),
    ]
