# Generated by Django 2.2.27 on 2022-08-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoot_setup', '0009_auto_20220812_1925'),
        ('shoot_setup', '0008_auto_20220812_2020'),
    ]

    operations = [
    ]
