# Generated by Django 2.2.27 on 2022-08-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoot_setup', '0010_merge_20220817_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shootsetup',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='shootsetup',
            name='client',
        ),
        migrations.RemoveField(
            model_name='shootsetup',
            name='director',
        ),
        migrations.RemoveField(
            model_name='shootsetup',
            name='grfx',
        ),
        migrations.RemoveField(
            model_name='shootsetup',
            name='on_sight',
        ),
        migrations.RemoveField(
            model_name='shootsetup',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='shootsetup',
            name='replay',
        ),
        migrations.RemoveField(
            model_name='shootsetup',
            name='technical_director',
        ),
    ]
