# Generated by Django 2.2.26 on 2022-09-12 12:29

from django.db import migrations, models
import shoot_setup.models


class Migration(migrations.Migration):

    dependencies = [
        ('shoot_setup', '0011_auto_20220818_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shootimage',
            name='background_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=shoot_setup.models.ShootImage.image_upload_dir, verbose_name='Background Image'),
        ),
    ]
