# Generated by Django 2.2.26 on 2023-01-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoot_setup', '0013_shootsetup_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='shootimage',
            name='background_image_base64',
            field=models.CharField(blank=True, max_length=900000, null=True, verbose_name='Background Image Base 64'),
        ),
    ]
