version: "3"

services:
  web:
    build:
      context: .
      args:
        SECRET_KEY: ${SECRET_KEY}
    env_file: .env
    volumes:
      - ./:/opt/webapp
    ports:
      - "8000:8000"
    # Added Command for hot reloading in dev server
    # command: > 
    #   sh -c "python3 manage.py runserver 0.0.0.0:8000"
  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 1234
      PGDATA: /var/lib/postgresql/data/air
    volumes:
      - postgres-data:/var/lib/postgresql/data/air
    ports:
      - "5432:5432"
  redis:
    image: redis:5
    ports:
      - "6379:6379"

volumes:
  postgres-data:

