# Generated by Django 2.2.27 on 2022-02-25 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100, verbose_name='Project Id')),
                ('name', models.CharField(max_length=100, verbose_name='Project Name')),
                ('client', models.CharField(max_length=100, verbose_name='Client')),
                ('shoot_date', models.DateTimeField(blank=True, null=True, verbose_name='Shoot Date')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Location')),
                ('image', models.ImageField(blank=True, null=True, upload_to=project.models.Project.project_upload_dir, verbose_name='Image')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='project_owner')),
            ],
        ),
    ]
