# Generated by Django 2.2.27 on 2022-02-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20220225_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='shoot_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Shoot End Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='shoot_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Shoot Start Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='shoot_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Shhot Time'),
        ),
    ]
