# Generated by Django 2.2.27 on 2022-03-03 13:06

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='cover_image',
        ),
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=project.models.Project.project_logo_upload_dir, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'Archive'), (1, 'Active')], default=1),
        ),
    ]
