# Generated by Django 2.2.27 on 2022-03-03 13:08

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20220303_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=project.models.Project.project_upload_dir, verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=project.models.Project.project_logo_upload_dir, verbose_name='Logo'),
        ),
    ]
