# Generated by Django 2.2.27 on 2022-03-15 09:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20220303_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
