# Generated by Django 2.2.27 on 2022-04-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20220414_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
    ]
