# Generated by Django 2.2.27 on 2022-05-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_project_is_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='Is Removed'),
        ),
    ]
