# Generated by Django 2.2.27 on 2022-08-12 19:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_project_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
