# Generated by Django 2.2.27 on 2022-08-18 13:08

from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20220812_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title Id')),
                ('url', models.CharField(blank=True, max_length=250, null=True, verbose_name='Url')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to=project.models.ProjectFiles.project_file_upload_dir, verbose_name='Logo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_files', to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectComms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title Id')),
                ('url', models.CharField(blank=True, max_length=250, null=True, verbose_name='Url')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_comms', to='project.Project')),
            ],
        ),
    ]
