# Generated by Django 2.2.26 on 2022-09-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_projectcomms_projectfiles_projectlinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcomms',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='projectlinks',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
    ]
