# Generated by Django 2.2.26 on 2022-09-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20220902_1018'),
        ('project', '0015_auto_20220831_0853'),
    ]

    operations = [
    ]
