# Generated by Django 2.2.26 on 2022-09-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_merge_20220905_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=250, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Project Id'),
        ),
        migrations.AlterField(
            model_name='projectcomms',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='projectcomms',
            name='type',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='projectlinks',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Title'),
        ),
    ]
