export default User_Role_Details = [
  {
    id: 1,
    name: 'Admin',
    permissions: [
      'CREATE_PROJECT',
      'EDIT_PROJECT_DETAILS',
      'ARCHIVE_PROJECT',
      'PROJECTS_SCREEN_VISABILITY',
      'SHOOT_SETUP_SCREEN',
      'VIDEO_AUDIO_ROUTING',
      'CAMERA_ASSIGN',
      'CAMERA_CONTROL',
      'COMMS',
      'EC2_CREATE',
      'EC2_ACCESS',
      'MULTIVIEW',
      'PROGRAM_FEED_FILE',
      'UPLOAD_FILE',
      'FILE_MOVEMENT',
      'USAGE_AND_BILLING',
      'EDIT_SETUP_SCREEN',
      'MEDIA_ASSET_MGMNT',
      'QR_SCAN',
    ],
  },
  {
    id: 2,
    name: 'Producer',
    permissions: [
      'CREATE_PROJECT',
      'EDIT_PROJECT_DETAILS',
      'SHOOT_SETUP_SCREEN',
      'VIDEO_AUDIO_ROUTING',
      'CAMERA_ASSIGN',
      'CAMERA_CONTROL',
      'COMMS',
      'EC2_CREATE',
      'EC2_ACCESS',
      'MULTIVIEW',
      'PROGRAM_FEED_FILE',
      'UPLOAD_FILE_MOVEMENT',
      'EDIT_SETUP_SCREEN',
      'MEDIA_ASSET_MGMNT',
      'QR_SCAN',
    ],
  },
  {
    id: 3,
    name: 'Director',
    permissions: [
      'SHOOT_SETUP_SCREEN',
      'VIDEO_AUDIO_ROUTING',
      'CAMERA_ASSIGN',
      'CAMERA_CONTROL',
      'COMMS',
      'EC2_CREATE',
      'EC2_ACCESS',
      'MULTIVIEW',
      'PROGRAM_FEED_FILE',
      'UPLOAD_FILE_MOVEMENT',
      'EDIT_SETUP_SCREEN',
      'MEDIA_ASSET_MGMNT',
      'QR_SCAN',
    ],
  },
  {
    id: 4,
    name: 'Technical_Director',
    permissions: [
      'SHOOT_SETUP_SCREEN',
      'VIDEO_AUDIO_ROUTING',
      'CAMERA_ASSIGN',
      'CAMERA_CONTROL',
      'COMMS',
      'EC2_CREATE',
      'EC2_ACCESS',
      'MULTIVIEW',
      'PROGRAM_FEED_FILE',
      'UPLOAD_FILE_MOVEMENT',
      'EDIT_SETUP_SCREEN',
      'MEDIA_ASSET_MGMNT',
      'QR_SCAN',
    ],
  },
  {
    id: 5,
    name: 'Camera_Op',
    permissions: [
      'COMMS',
      'EC2_CREATE',
      'EC2_ACCESS',
      'MULTIVIEW',
      'PROGRAM_FEED_FILE',
      'MEDIA_ASSET_MGMNT',
      'QR_SCAN',
    ],
  },
  {
    id: 6,
    name: 'Field_Crew',
    permissions: [
      'CAMERA_CONTROL',
      'COMMS',
      'MULTIVIEW',
      'PROGRAM_FEED_FILE',
      'QR_SCAN',
    ],
  },
  {
    id: 7,
    name: 'Client',
    permissions: [
      'MULTIVIEW',
      'PROGRAM_FEED_FILE',
      'UPLOAD_FILE_MOVEMENT',
      'MEDIA_ASSET_MGMNT',
    ],
  },
  {
    id: 8,
    name: 'Talent',
    permissions: ['COMMS', 'MULTIVIEW', 'PROGRAM_FEED_FILE'],
  },
  {
    id: 9,
    name: 'Edit_Op',
    permissions: [
      'EC2_ACCESS',
      'UPLOAD_FILE_MOVEMENT',
      'EDIT_SETUP_SCREEN',
      'MEDIA_ASSET_MGMNT',
    ],
  },
  {
    id: 10,
    name: 'Grfx_Op',
    permissions: [
      'EC2_ACCESS',
      'UPLOAD_FILE_MOVEMENT',
      'EDIT_SETUP_SCREEN',
      'MEDIA_ASSET_MGMNT',
    ],
  },
  {
    id: 11,
    name: 'Audio_Op',
    permissions: [
      'EC2_ACCESS',
      'UPLOAD_FILE_MOVEMENT',
      'EDIT_SETUP_SCREEN',
      'MEDIA_ASSET_MGMNT',
    ],
  },
  {
    id: 12,
    name: 'Play_Op',
    permissions: [
      'EC2_ACCESS',
      'UPLOAD_FILE_MOVEMENT',
      'EDIT_SETUP_SCREEN',
      'MEDIA_ASSET_MGMNT',
    ],
  },
  {
    id: 13,
    name: 'No_Role',
    permissions: [],
  },
];
