# Generated by Django 2.2.27 on 2022-04-01 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20220401_2011'),
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PermissionTypes',
            new_name='PermissionType',
        ),
    ]
