# Generated by Django 2.2.27 on 2022-04-01 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20220401_2025'),
        ('permission', '0002_auto_20220401_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissiontype',
            name='user_type',
        ),
        migrations.AddField(
            model_name='permissiontype',
            name='role',
            field=models.OneToOneField(default=13, on_delete=django.db.models.deletion.CASCADE, to='users.Role', verbose_name='Global Role'),
        ),
    ]
