# Generated by Django 2.2.27 on 2022-04-06 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0004_projectpermissionmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiontype',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Role', verbose_name='Global Role'),
        ),
        migrations.AlterField(
            model_name='projectpermissionmapping',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Role', verbose_name='Project Role'),
        ),
    ]
