# Generated by Django 2.2.27 on 2022-08-12 19:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0008_auto_20220406_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiontype',
            name='permissions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
