# Generated by Django 2.2.27 on 2022-08-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0012_auto_20220818_1252'),
        ('permission', '0012_auto_20220823_1036'),
    ]

    operations = [
    ]
