# Generated by Django 2.2.26 on 2022-10-11 11:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0014_auto_20220830_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationPermissionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Admin'), (2, 'Producer'), (3, 'Crew'), (4, 'No Role')], default=4)),
                ('permissions', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
    ]
