# Generated by Django 2.2.27 on 2022-03-06 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gear.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0007_auto_20220303_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=gear.models.Camera.icon_upload_dir, verbose_name='Icon')),
                ('owner_name', models.CharField(max_length=100, verbose_name='Gear Owner Name')),
                ('nick_name', models.CharField(blank=True, max_length=100, verbose_name='Nick Name')),
                ('lan_ip', models.CharField(blank=True, max_length=100, verbose_name='Lan IP')),
                ('public_ip', models.CharField(blank=True, max_length=100, verbose_name='Public IP')),
                ('air_id', models.CharField(max_length=100, verbose_name='AIR ID')),
                ('internal_record_format', models.CharField(blank=True, max_length=100, verbose_name='Internal Record Format')),
                ('external_stream_format', models.CharField(blank=True, max_length=100, verbose_name='External Stream Format')),
                ('firmware_version', models.CharField(blank=True, max_length=100, verbose_name='Firmware Version')),
                ('subscription_status', models.IntegerField(default=1, max_length=100, verbose_name='Subscription Status')),
                ('current_project_assignment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='current_project')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='gear_owner')),
            ],
        ),
    ]
