# Generated by Django 2.2.27 on 2022-03-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='air_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='AIR ID'),
        ),
    ]
