# Generated by Django 2.2.27 on 2022-03-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0003_camera__type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='_type',
            field=models.IntegerField(choices=[(1, 'Camera'), (2, 'Something')], default=1),
        ),
    ]
