# Generated by Django 2.2.27 on 2022-03-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0004_auto_20220311_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='_type',
            field=models.IntegerField(choices=[(1, 'Camera'), (2, 'Switcher instance Standard'), (3, 'Switcher instance L'), (4, 'Switcher instance XL'), (5, 'Replay instance')], default=1),
        ),
        migrations.AlterField(
            model_name='camera',
            name='external_stream_format',
            field=models.IntegerField(choices=[(1, '1080p 25fps'), (2, '1080p 30fps'), (3, '1080p 50fps'), (4, '1080p 60fps'), (5, '4k 25fps'), (6, '4k 30fps'), (7, '4k 50fps'), (8, '4k 60fps')], default=1),
        ),
        migrations.AlterField(
            model_name='camera',
            name='internal_record_format',
            field=models.IntegerField(choices=[(1, '1080p 25fps'), (2, '1080p 30fps'), (3, '1080p 50fps'), (4, '1080p 60fps'), (5, '4k 25fps'), (6, '4k 30fps'), (7, '4k 50fps'), (8, '4k 60fps')], default=1),
        ),
    ]
