# Generated by Django 2.2.27 on 2022-04-03 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_project_properties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gear', '0005_auto_20220317_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='owner',
        ),
        migrations.CreateModel(
            name='CameraAssignedToProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0, verbose_name='X position of the Camera.')),
                ('y', models.IntegerField(default=0, verbose_name='Y position of the Camera.')),
                ('rotate', models.IntegerField(default=0, verbose_name='Rotation of the Camera.')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gear.Camera')),
                ('camera_operator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
    ]
