# Generated by Django 2.2.27 on 2022-04-03 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0006_auto_20220403_0718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cameraassignedtoproject',
            old_name='rotate',
            new_name='camera_rotation',
        ),
        migrations.RenameField(
            model_name='cameraassignedtoproject',
            old_name='x',
            new_name='camera_x',
        ),
        migrations.RenameField(
            model_name='cameraassignedtoproject',
            old_name='y',
            new_name='camera_y',
        ),
        migrations.AddField(
            model_name='cameraassignedtoproject',
            name='camera_operator_rotation',
            field=models.IntegerField(default=0, verbose_name='X position of the Camera Operator.'),
        ),
        migrations.AddField(
            model_name='cameraassignedtoproject',
            name='camera_operator_x',
            field=models.IntegerField(default=0, verbose_name='X position of the Camera Operator.'),
        ),
        migrations.AddField(
            model_name='cameraassignedtoproject',
            name='camera_operator_y',
            field=models.IntegerField(default=0, verbose_name='X position of the Camera Operator.'),
        ),
        migrations.AlterField(
            model_name='cameraassignedtoproject',
            name='camera_operator',
            field=models.ForeignKey(blank=True, null=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
