# Generated by Django 2.2.27 on 2022-04-03 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0007_auto_20220403_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraassignedtoproject',
            name='camera_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
