# Generated by Django 2.2.27 on 2022-04-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0009_auto_20220403_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraassignedtoproject',
            name='camera_operator_rotation',
            field=models.FloatField(default=0, verbose_name='X position of the Camera Operator.'),
        ),
        migrations.AlterField(
            model_name='cameraassignedtoproject',
            name='camera_operator_x',
            field=models.FloatField(default=0, verbose_name='X position of the Camera Operator.'),
        ),
        migrations.AlterField(
            model_name='cameraassignedtoproject',
            name='camera_operator_y',
            field=models.FloatField(default=0, verbose_name='X position of the Camera Operator.'),
        ),
        migrations.AlterField(
            model_name='cameraassignedtoproject',
            name='camera_rotation',
            field=models.FloatField(default=0, verbose_name='Rotation of the Camera.'),
        ),
        migrations.AlterField(
            model_name='cameraassignedtoproject',
            name='camera_x',
            field=models.FloatField(default=0, verbose_name='X position of the Camera.'),
        ),
        migrations.AlterField(
            model_name='cameraassignedtoproject',
            name='camera_y',
            field=models.FloatField(default=0, verbose_name='Y position of the Camera.'),
        ),
    ]
