# Generated by Django 2.2.27 on 2022-04-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0010_auto_20220403_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='current_project_assignment',
        ),
    ]
