# Generated by Django 2.2.27 on 2022-04-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0011_remove_camera_current_project_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraassignedtoproject',
            name='camera_image_x',
            field=models.FloatField(default=0, verbose_name='X position of the Camera Image.'),
        ),
        migrations.AddField(
            model_name='cameraassignedtoproject',
            name='camera_image_y',
            field=models.FloatField(default=0, verbose_name='Y position of the Camera Image.'),
        ),
        migrations.AddField(
            model_name='cameraassignedtoproject',
            name='camera_placeholder',
            field=models.CharField(blank=True, default=None, max_length=3, null=True, verbose_name='Camera Placeholder.'),
        ),
    ]
