# Generated by Django 2.2.27 on 2022-04-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0012_auto_20220418_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraassignedtoproject',
            name='camera_placeholder',
            field=models.CharField(blank=True, default=None, max_length=3, null=True, verbose_name='Camera Placeholder.'),
        ),
    ]
