# Generated by Django 2.2.27 on 2022-04-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0014_auto_20220418_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='air_id',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='AIR ID'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='nick_name',
            field=models.CharField(max_length=100, verbose_name='Nick Name'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Gear Owner Name'),
        ),
    ]
