# Generated by Django 2.2.27 on 2022-05-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0017_auto_20220505_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraassignedtoproject',
            name='camera_placeholder',
            field=models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Camera Placeholder.'),
        ),
    ]
