# Generated by Django 2.2.27 on 2022-07-13 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
        ('gear', '0018_auto_20220505_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='organisation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_camera', to='organisation.Organisation'),
        ),
    ]
