# Generated by Django 2.2.27 on 2022-08-10 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0011_auto_20220505_1716'),
        ('gear', '0018_auto_20220505_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirCamera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(blank=True, max_length=100, verbose_name='Gear Owner Name')),
                ('nick_name', models.CharField(max_length=100, verbose_name='Nick Name')),
                ('lan_ip', models.CharField(blank=True, max_length=100, verbose_name='Lan IP')),
                ('public_ip', models.CharField(blank=True, max_length=100, verbose_name='Public IP')),
                ('air_id', models.CharField(max_length=100, unique=True, verbose_name='AIR ID')),
                ('internal_record_format', models.IntegerField(choices=[(1, '1080p 25fps'), (2, '1080p 30fps'), (3, '1080p 50fps'), (4, '1080p 60fps'), (5, '4k 25fps'), (6, '4k 30fps'), (7, '4k 50fps'), (8, '4k 60fps')], default=1)),
                ('external_stream_format', models.IntegerField(choices=[(1, '1080p 25fps'), (2, '1080p 30fps'), (3, '1080p 50fps'), (4, '1080p 60fps'), (5, '4k 25fps'), (6, '4k 30fps'), (7, '4k 50fps'), (8, '4k 60fps')], default=1)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AirInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_type', models.CharField(choices=[('VIMIX_MAIN', 'VMIX Main'), ('VIMIX_REPLY', 'VMIX Reply')], max_length=100, verbose_name='Instance Type')),
                ('instance_size', models.CharField(choices=[('STANDARD', 'Standard'), ('L', 'L'), ('XL', 'XL')], max_length=100, verbose_name='Instance Size')),
                ('owner_name', models.CharField(blank=True, max_length=100, verbose_name='Gear Owner Name')),
                ('nick_name', models.CharField(max_length=100, verbose_name='Nick Name')),
                ('lan_ip', models.CharField(blank=True, max_length=100, verbose_name='Lan IP')),
                ('public_ip', models.CharField(blank=True, max_length=100, verbose_name='Public IP')),
                ('air_id', models.CharField(max_length=100, unique=True, verbose_name='AIR ID')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='camera',
            name='_type',
            field=models.IntegerField(choices=[(2, 'Switcher instance Standard'), (3, 'Switcher instance L'), (4, 'Switcher instance XL'), (5, 'Replay instance')], default=1),
        ),
        migrations.CreateModel(
            name='AirInstanceAssignedToProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_operators', models.ManyToManyField(blank=True, related_name='air_instance', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gear.AirInstance')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='AirCameraAssignedToProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_x', models.FloatField(default=0, verbose_name='X position of the Camera.')),
                ('camera_y', models.FloatField(default=0, verbose_name='Y position of the Camera.')),
                ('camera_image_x', models.FloatField(default=0, verbose_name='X position of the Camera Image.')),
                ('camera_image_y', models.FloatField(default=0, verbose_name='Y position of the Camera Image.')),
                ('camera_rotation', models.FloatField(default=0, verbose_name='Rotation of the Camera.')),
                ('camera_placeholder', models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Camera Placeholder.')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gear.AirCamera')),
                ('camera_operators', models.ManyToManyField(blank=True, related_name='air_camera', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
    ]
