# Generated by Django 2.2.27 on 2022-07-13 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gear', '0019_camera_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameraassignedtoproject',
            name='camera_operator',
        ),
        migrations.AddField(
            model_name='cameraassignedtoproject',
            name='camera_operator',
            field=models.ManyToManyField(blank=True, related_name='camera_operators', to=settings.AUTH_USER_MODEL, verbose_name='Camera Operators'),
        ),
    ]
