# Generated by Django 2.2.27 on 2022-08-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0020_auto_20220713_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='subscription_status',
            field=models.IntegerField(default=1, verbose_name='Subscription Status'),
        ),
    ]
