# Generated by Django 2.2.27 on 2022-08-13 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0020_auto_20220810_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircameraassignedtoproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_cameras', to='project.Project'),
        ),
        migrations.AlterField(
            model_name='airinstanceassignedtoproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_instances', to='project.Project'),
        ),
    ]
