# Generated by Django 2.2.27 on 2022-08-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0021_auto_20220812_1926'),
        ('gear', '0022_auto_20220814_2002'),
    ]

    operations = [
    ]
