# Generated by Django 2.2.27 on 2022-08-18 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0025_auto_20220818_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircameraassignedtoproject',
            old_name='assigned_camera',
            new_name='camera_operators',
        ),
    ]
