# Generated by Django 2.2.26 on 2022-08-30 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0026_auto_20220818_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircameraassignedtoproject',
            name='camera_operators',
            field=models.ManyToManyField(blank=True, related_name='air_camera', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AirCameraOperatorProjectAssignment',
        ),
    ]
