# Generated by Django 2.2.27 on 2022-08-31 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gear', '0028_auto_20220831_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircameraassignedtoproject',
            name='camera_image_x',
        ),
        migrations.RemoveField(
            model_name='aircameraassignedtoproject',
            name='camera_image_y',
        ),
        migrations.RemoveField(
            model_name='aircameraassignedtoproject',
            name='camera_operators',
        ),
        migrations.RemoveField(
            model_name='aircameraassignedtoproject',
            name='camera_placeholder',
        ),
        migrations.RemoveField(
            model_name='aircameraassignedtoproject',
            name='camera_rotation',
        ),
        migrations.RemoveField(
            model_name='aircameraassignedtoproject',
            name='camera_x',
        ),
        migrations.RemoveField(
            model_name='aircameraassignedtoproject',
            name='camera_y',
        ),
        migrations.RenameModel(
            old_name='AirCameraOperatorProjectAssignment',
            new_name='AirOperatorAssignedToShoot',
        ),
        migrations.CreateModel(
            name='AirConnectionsToShoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_x', models.FloatField(default=0, verbose_name='X position of the Camera.')),
                ('camera_y', models.FloatField(default=0, verbose_name='Y position of the Camera.')),
                ('camera_image_x', models.FloatField(default=0, verbose_name='X position of the Camera Image.')),
                ('camera_image_y', models.FloatField(default=0, verbose_name='Y position of the Camera Image.')),
                ('camera_rotation', models.FloatField(default=0, verbose_name='Rotation of the Camera.')),
                ('camera_placeholder', models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Camera Placeholder.')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_connection', to='gear.AirCameraAssignedToProject')),
                ('camera_operators', models.ManyToManyField(blank=True, related_name='air_connections', to='gear.AirOperatorAssignedToShoot')),
            ],
        ),
    ]
