# Generated by Django 2.2.27 on 2022-08-31 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20220831_0853'),
        ('gear', '0030_airconnectionstoshoot_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='airoperatorassignedtoshoot',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='air_operator', to='project.Project'),
            preserve_default=False,
        ),
    ]
