# Generated by Django 2.2.26 on 2022-10-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0032_auto_20221011_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircamera',
            name='external_stream_format',
            field=models.CharField(blank=True, max_length=255, verbose_name='External Record Format'),
        ),
        migrations.AlterField(
            model_name='aircamera',
            name='internal_record_format',
            field=models.CharField(blank=True, max_length=255, verbose_name='Internal Record Format'),
        ),
    ]
