# Generated by Django 2.2.26 on 2022-10-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0034_auto_20221013_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationownedcamera',
            name='lan_ip',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lan IP'),
        ),
        migrations.AddField(
            model_name='organisationownedcamera',
            name='public_ip',
            field=models.CharField(blank=True, max_length=100, verbose_name='Public IP'),
        ),
    ]
