# Generated by Django 2.2.26 on 2022-10-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0035_auto_20221013_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationownedcamera',
            name='latest_invoice_id',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
