# Generated by Django 2.2.26 on 2022-10-14 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_auto_20220902_1018'),
        ('gear', '0036_organisationownedcamera_latest_invoice_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organisationownedcamera',
            unique_together={('organisation', 'camera')},
        ),
    ]
