# Generated by Django 2.2.26 on 2022-10-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0038_auto_20221017_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='airinstanceactivitytracker',
            name='calculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='airinstanceactivitytracker',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time'),
        ),
    ]
