# Generated by Django 2.2.26 on 2022-10-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0039_auto_20221018_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='airinstancebillingtracker',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Total Amount'),
        ),
    ]
