# Generated by Django 2.2.26 on 2022-11-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0041_airinstancehourstracker_calculated'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationownedcamera',
            name='is_deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
