# Generated by Django 2.2.26 on 2022-11-08 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0042_organisationownedcamera_is_deactivated'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircamera',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Last Activity'),
            preserve_default=False,
        ),
    ]
