# Generated by Django 2.2.26 on 2022-11-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0043_aircamera_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircamera',
            name='camera_field_status',
            field=models.IntegerField(default=0),
        ),
    ]
