# Generated by Django 2.2.26 on 2022-11-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0044_aircamera_camera_field_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircamera',
            name='nick_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nick Name'),
        ),
    ]
