# Generated by Django 2.2.26 on 2023-02-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0046_auto_20221124_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationownedcamera',
            name='payment_session_id',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
