# Generated by Django 2.2.27 on 2022-08-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0021_auto_20220812_1926'),
        ('organisation', '0002_auto_20220812_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='camera',
            field=models.ManyToManyField(related_name='organisation_camera', to='gear.AirCamera', verbose_name='Organisation Camera'),
        ),
    ]
