# Generated by Django 2.2.27 on 2022-08-18 13:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisation', '0004_organisation_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organisationmembermapping',
            unique_together={('organisation', 'user')},
        ),
    ]
