# Generated by Django 2.2.26 on 2022-09-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_auto_20220818_1308'),
    ]

    operations = [
        

        migrations.AlterField(
            model_name='organisation',
            name='camera',
            field=models.ManyToManyField(related_name='organisation_camera', to='gear.AirCamera', verbose_name='Organisation Camera'),
        ),

    ]
