# Generated by Django 2.2.26 on 2022-11-05 17:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_auto_20220902_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationComms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=250, null=True, verbose_name='Type')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title')),
                ('url', models.CharField(blank=True, max_length=250, null=True, verbose_name='Url')),
                ('is_copy_to_projects', models.BooleanField(default=False, verbose_name='Copy to projects')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_comms', to='organisation.Organisation')),
            ],
        ),
    ]
