# Generated by Django 2.2.26 on 2022-11-05 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0008_colelctionitem_collection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColelctionItem',
            new_name='CollectionItem',
        ),
        migrations.RenameField(
            model_name='collectionitem',
            old_name='colelction',
            new_name='collection',
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('organisation', 'name')},
        ),
    ]
