# Generated by Django 2.2.26 on 2022-11-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0010_auto_20221118_1811'),
    ]

    operations = [
        
    ]
