# Generated by Django 2.2.26 on 2022-11-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0011_auto_20221124_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='camera',
            field=models.ManyToManyField(related_name='organisation_camera', to='gear.AirCamera', verbose_name='Organisation Camera'),
        ),
    ]
