# Generated by Django 2.2.26 on 2022-11-25 10:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0012_auto_20221124_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('url', models.CharField(max_length=250, verbose_name='Url')),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
