# Generated by Django 2.2.26 on 2022-12-01 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0013_urltags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='camera',
        ),
    ]
