# Generated by Django 2.2.26 on 2022-12-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0015_organisation_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='wasabi_bucket_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Wasabi Bucket Name'),
        ),
    ]
