# Generated by Django 2.2.26 on 2023-01-12 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0017_mediametadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediametadata',
            name='organisation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_media_metadata', to='organisation.Organisation'),
        ),
    ]
