# Generated by Django 2.2.26 on 2023-01-20 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0018_mediametadata_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionitem',
            name='url',
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='key',
            field=models.CharField(max_length=250, null=True, verbose_name='key'),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='organisation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_collection_items', to='organisation.Organisation'),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='thumbnail_url',
            field=models.URLField(max_length=250, null=True, verbose_name='Url'),
        ),
    ]
