# Generated by Django 2.2.26 on 2023-01-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0020_collectionitem_bucket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='collectionitem',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='mediametadata',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='urltags',
            name='is_removed',
        ),
    ]
