# Generated by Django 2.2.26 on 2022-09-16 21:10

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Month'), (2, 'One Time')], default=1)),
                ('price_supporting_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Price Supporting Text')),
                ('currency', models.CharField(blank=True, default='usd', max_length=255, null=True, verbose_name='Currency')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('stripe_product_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Product Id')),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Price Id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
