# Generated by Django 2.2.26 on 2022-09-16 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Packages',
            new_name='Package',
        ),
        migrations.CreateModel(
            name='PurchaseSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_pm_id', models.CharField(blank=True, editable=False, max_length=100)),
                ('stripe_subcription_id', models.CharField(blank=True, editable=False, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Subscription start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Subscription end date')),
                ('invoice_id', models.CharField(blank=True, editable=False, max_length=100)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('payment_fail_reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_card_id', models.CharField(blank=True, editable=False, max_length=100)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_package', to='payment.Package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_purchase_package', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
