# Generated by Django 2.2.26 on 2022-09-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20220916_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesubscription',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
