# Generated by Django 2.2.26 on 2022-10-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20221003_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='storage_type',
            field=models.CharField(blank=True, choices=[('gb', 'GB'), ('tb', 'TB')], default=None, max_length=100, null=True),
        ),
    ]
