# Generated by Django 2.2.26 on 2022-10-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20221003_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesubscription',
            name='payment_session_id',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
