# Generated by Django 2.2.26 on 2022-10-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_purchasesubscription_payment_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasesubscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Subscription end date'),
        ),
        migrations.AlterField(
            model_name='purchasesubscription',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Subscription start date'),
        ),
    ]
