# Generated by Django 2.2.26 on 2022-10-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20221003_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesubscription',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
