# Generated by Django 2.2.26 on 2022-10-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_purchasesubscription_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesubscription',
            name='stripe_subcription_item_id',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
