# Generated by Django 2.2.26 on 2022-10-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_purchasesubscription_stripe_subcription_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasesubscription',
            old_name='stripe_subcription_id',
            new_name='stripe_subscription_id',
        ),
        migrations.RenameField(
            model_name='purchasesubscription',
            old_name='stripe_subcription_item_id',
            new_name='stripe_subscription_item_id',
        ),
    ]
