# Generated by Django 2.2.26 on 2022-10-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20221004_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Invoice Id'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Invoice Url'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
    ]
