# Generated by Django 2.2.26 on 2022-10-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_auto_20221014_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.IntegerField(choices=[(1, 'Storage'), (2, 'Camera'), (3, 'Instance')], default=1),
        ),
    ]
