# Generated by Django 2.2.27 on 2022-02-22 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('nick_name', models.CharField(max_length=100, verbose_name='Nick Name')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=users.models.UserInformation.pic_upload_dir, verbose_name='Profile Image')),
                ('company_name', models.CharField(max_length=100, verbose_name='Is Active')),
                ('job_title', models.CharField(max_length=100, verbose_name='Job Title')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('country', models.CharField(max_length=100, verbose_name='Location')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='business_user')),
            ],
        ),
    ]
