# Generated by Django 2.2.27 on 2022-02-22 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_country_userinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=250, verbose_name='Code')),
                ('is_claim', models.BooleanField(default=False, verbose_name='Is Claim')),
                ('is_password_change', models.BooleanField(default=False, verbose_name='Is Password Change')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reset_token_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-user'],
            },
        ),
    ]
