# Generated by Django 2.2.27 on 2022-02-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_resetpasswordtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='company_name',
            field=models.CharField(max_length=100, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='nick_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nick Name'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Phone'),
        ),
    ]
