# Generated by Django 2.2.27 on 2022-03-02 08:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_activitytracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Role Name')),
                ('description', models.CharField(blank=True, max_length=512, verbose_name='Description')),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 3, 2, 8, 49, 23, 829882, tzinfo=utc))),
                ('modified', models.DateTimeField(default=datetime.datetime(2022, 3, 2, 8, 49, 23, 829907, tzinfo=utc))),
                ('is_removed', models.BooleanField(default=False, verbose_name='Is Removed')),
            ],
        ),
    ]
