# Generated by Django 2.2.27 on 2022-04-01 20:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20220401_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 1, 20, 24, 59, 963214, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='role',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 1, 20, 24, 59, 963247, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='role',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='users.Role', verbose_name='Role'),
        ),
    ]
