# Generated by Django 2.2.27 on 2022-07-23 10:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20220418_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 23, 10, 47, 45, 603133, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='role',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 23, 10, 47, 45, 603158, tzinfo=utc)),
        ),
    ]
