# Generated by Django 2.2.27 on 2022-05-05 17:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_auto_20220505_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 17, 19, 40, 132976, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='role',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 17, 19, 40, 133001, tzinfo=utc)),
        ),
    ]
