# Generated by Django 2.2.27 on 2022-05-05 17:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_auto_20220505_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 17, 23, 3, 69012, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='role',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 17, 23, 3, 69036, tzinfo=utc)),
        ),
    ]
