# Generated by Django 2.2.27 on 2022-07-12 19:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20220505_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 19, 13, 14, 428533, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='role',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 19, 13, 14, 428556, tzinfo=utc)),
        ),
    ]
