# Generated by Django 2.2.27 on 2022-08-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_auto_20220712_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='first_login',
            field=models.BooleanField(default=True, verbose_name='First Login'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='global_role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Producer'), (3, 'Crew'), (4, 'No Role')], default=4),
        ),
    ]
