# Generated by Django 2.2.27 on 2022-07-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_auto_20220712_1915'),
        ('users', '0045_auto_20220723_1047'),
    ]

    operations = [
    ]
