# Generated by Django 2.2.27 on 2022-08-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_auto_20220812_1922'),
        ('users', '0050_merge_20220723_1415'),
    ]

    operations = [
    ]
