# Generated by Django 2.2.27 on 2022-08-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_auto_20220818_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='global_member',
            field=models.BooleanField(default=True, verbose_name='Global Search'),
        ),
    ]
