# Generated by Django 2.2.27 on 2022-08-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_userinformation_global_member'),
        ('users', '0052_auto_20220817_1005'),
    ]

    operations = [
    ]
