# Generated by Django 2.2.26 on 2022-09-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_auto_20220908_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe Customer Id'),
        ),
    ]
