# Generated by Django 2.2.26 on 2022-09-26 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_inviteduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inviteduser',
            old_name='token',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='inviteduser',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_project', to='project.Project', verbose_name='Invited Project'),
        ),
        migrations.AlterField(
            model_name='inviteduser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Producer'), (3, 'Crew'), (4, 'No Role')], default=4),
        ),
    ]
