# Generated by Django 2.2.26 on 2022-09-26 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_auto_20220926_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteduser',
            name='email',
            field=models.CharField(editable=False, max_length=250, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='inviteduser',
            name='project',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_project', to='project.Project', verbose_name='Invited Project'),
        ),
        migrations.AlterField(
            model_name='inviteduser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Producer'), (3, 'Crew'), (4, 'No Role')], default=4, editable=False),
        ),
    ]
