# Generated by Django 2.2.26 on 2022-10-06 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_auto_20220902_1018'),
        ('users', '0064_auto_20220928_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteduser',
            name='organisation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_organisation', to='organisation.Organisation', verbose_name='Invited Organisation'),
        ),
    ]
