# Generated by Django 2.2.26 on 2022-10-06 18:27

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_inviteduser_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidateUserEmail',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(editable=False, max_length=250, verbose_name='Email')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Is Expired')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
