# Generated by Django 2.2.26 on 2022-10-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_resetpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validateuseremail',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Is Confirmed'),
        ),
    ]
